config/routes.rb
Rails.application.routes.draw do
  get 'admin/users'

  get 'admin/revoke_admin'

  get 'admin/grant_admin'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/' => 'home#index'
  post '/create_tweet' => 'home#create_tweet'
  post '/create_tweet_json' => 'home#create_tweet_json'

  post '/like' => 'home#like'
  post '/like_tweet_json' => 'home#like_tweet_json'
  post '/create_tweet_remote' => 'home#create_tweet_remote'

  post '/follow' => 'home#follow'

  get '/index_api' => 'home#index_api'
  get '/search' => 'home#search'
  get '/users' => 'home#users'
  get '/followers' => 'home#followers'
  get '/followees' => 'home#followees'

  get '/profile/picture' => 'home#update_picture', as: "update_picture"
  post '/profile/picture' => 'home#save_picture', as: "save_picture"
  get '/profile/:id' => 'home#profile', as: "user_profile"
  post '/update_profile' => 'home#update_profile'
  get '/autocomplete_user_email' => 'home#autocomplete_user_email'

  post '/index_tweets' => 'home#index_tweets'
  mount Resque::Server, :at => "/resque"
  delete '/delete_tweet' => 'home#delete_tweet'

  namespace :api do
    namespace :v1 do
      post '/sign_in' => 'users_api#sign_in'
      post '/generate_otp' => 'users_api#generate_otp'
      post '/verify_otp' => 'users_api#verify_otp'
      get '/feed' => 'users_logged_in#feed'
      get '/followers' => 'users_logged_in#followers'
      get '/followees' => 'users_logged_in#followees'

    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  autocomplete :user, :email


  def index
    @page_number = 0
    if params[:page]
        @page_number = params[:page].to_i
    end

    @tweets = current_user.feed page_number: @page_number
    search = params[:search]

    @page_count = current_user.page_count

    if search
      query = "content like '%#{search}%' "
      @tweets = @tweets.where(query)
    end

  end

  def index_tweets
    @page_number = params[:page].to_i
    @tweets = current_user.feed page_number: @page_number
    respond_to do |format|
      format.js{

      }
    end
  end

  def search
    user = User.find_by_email(params[:email])
    return redirect_to user_profile_path(user.id) unless user.nil?
    redirect_to root_path, notice: "No Matches Found!!!!"
  end


  def index_api
    render json: current_user.feed
  end

  def create_tweet
    current_user.tweets.create(content: params[:content])
    return redirect_to '/'
  end

  def create_tweet_json
    tweet = current_user.tweets.create(content: params[:content])
    render json: tweet
  end

  def create_tweet_remote
    @tweet = current_user.tweets.create(content: params[:content])
    respond_to do |format|
      format.js{

      }
    end
  end

  def like
    tweet_id = params[:tweet_id]
    return redirect_to root_path, notice: "You can't like your own tweet!!!" if Tweet.find(tweet_id).user_id == current_user.id
    like = current_user.likes.where(tweet_id: tweet_id).first
    if like
      like.destroy
    else
      current_user.likes.create(tweet_id: tweet_id)
    end

    redirect_to '/'
  end

  def like_tweet_json
    tweet_id = params[:tweet_id]
    like = current_user.likes.where(tweet_id: tweet_id).first
    if like
      like.destroy
      like_state = false
    else
      like = current_user.likes.create(tweet_id: tweet_id)
      like_state = true
    end


    data = Hash.new
    data["tweet_id"] = tweet_id
    data["like"] = like
    data["like_state"] = like_state

    render json: data
  end

  def follow
    followee_id = params[:followee_id]
    follow_mapping = FollowMapping.where(:follower_id => current_user.id, :followee_id => followee_id).first
    unless follow_mapping
      follow_mapping = FollowMapping.create(:follower_id => current_user.id, :followee_id => followee_id)
    else
      follow_mapping.destroy
    end

    return redirect_to user_profile_path(followee_id)
  end

  def users
    @users = User.where('id != ?', current_user.id)
  end

  def followers
    @users = current_user.followers
  end

  def followees
    @users = current_user.followees
  end

  def profile
    email_id = params[:email]
    if params[:id]
      @user = User.find_by_id(params[:id])
    elsif email_id.nil?
      @user = User.find_by_email(email_id)
    end
    return redirect_to root_path, notice: "Invalid User!!!" if @user.nil?
    @tweets = @user.tweets
  end

  def update_picture
  end

  def save_picture
    p = params["profile_picture"]
    new_filename = SecureRandom.hex + "." + p.original_filename.split(".")[1]

    File.open(Rails.root.join('public', 'uploads', new_filename), 'wb') do |file|
      file.write(p.read)
    end

    current_user.profile_picture = new_filename
    current_user.save
    redirect_to user_profile_path(current_user.id)
  end

  def delete_tweet
    tweet = Tweet.find(params[:tweet_id])
    if current_user.admin? || (tweet.user_id == current_user.id) 
      tweet.destroy
    end
    redirect_to '/'
  end

end

app/helpers/home_helper.rb
module HomeHelper
	def constant_string
		"Constant"
	end
end

app/views/home/_tweet.html.erb
<div class="tweet">
  <div class="userImage inline">
    <div class="dummy">
      <img class="tweetImage" src="<%=tweet.user.profile_picture_url%>">
    </div>
  </div>

  <div class="content inline">
    <div class="userDetails">
      <div class="username inline"><a href="/profile/<%=tweet.user.id%>"><%= tweet.user.name %></a></div>
      <div class="time inline"><%= tweet.created_at.to_formatted_s(:short) %></div>
    </div>
    <div class="tweetContent"><%= tweet.content %></div>
    <div class="reactions">
    <% if Tweet.find(tweet.id).user_id != current_user.id %>
      <i class="fa fa-thumbs-o-up" aria-hidden="true" style="font-size: 22px; color: black;"><%= tweet.likes.count %></i>
          <% if tweet.likes.where(user_id: current_user.id).length > 0 %>
          <%= link_to "Unlike", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post, class: 'tweet_like_link', id: "tweet_#{tweet.id}", class: "btn small-btn" %>

      <% else %>
          <%= link_to "Like", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post, class: 'tweet_like_link', id: "tweet_#{tweet.id}", class: "btn small-btn" %>
      <% end %>
    <% end %>

<% if current_user.admin? || (current_user.id == tweet.user_id) %>
      <%= link_to 'Delete', url_for(controller: :home, action: :delete_tweet, tweet_id: tweet.id), method: :delete, class: "btn small-btn" %>


      <% end %>
    </div>


  </div>


</div>

app/views/home/_user.html.erb
<%= user.email %>,
<% unless user.followers.pluck(:id).include?(current_user.id) %>
    <%= link_to "Follow", url_for(controller: :home, action: :follow, followee_id: user.id), method: :post %>

<% else %>
    <%= link_to "Un Follow", url_for(controller: :home, action: :follow, followee_id: user.id), method: :post %>


<% end %>

app/views/home/_users.html.erb
<ul>
  <% users.each do |user| %>

      <li>
        <%= render 'user', :user => user %>
      </li>

  <% end %>

</ul>

app/views/home/create_tweet_remote.js.erb
$("#tweets").prepend("<%= escape_javascript(render 'tweet', :tweet => @tweet) %>");

app/views/home/followees.html.erb
<%= render 'users', :users => @users %>

app/views/home/followers.html.erb
<%= render 'users', :users => @users %>

app/views/home/index.html.erb
<section id="mainSection" id="top">
  <aside id="mainAside" class="userInfo">
    
      <div class="card">
		    <div class="card-content" style="padding: 0px;">
		      <%= image_tag current_user.profile_picture_url, class: "profile_picture" %>
		    </div>
		    <div class="card-tabs">
		      <ul class="tabs">
		        <li class="tab"><a class="active" href="#username">Name</a></li>
		        <li class="tab"><a href="#followers">Followers</a></li>
		        <li class="tab"><a href="#following">Following</a></li>
		      </ul>
		    </div>
		    <div class="card-content grey lighten-4">
		      <div id="username"><%=current_user.name%></div>
		      <div id="followers"><%=current_user.followers.count%></div>
		      <div id="following"><%=current_user.followees.count%></div>
		    </div>
		  </div>
  </aside>
  <main id="mainMain">
		<%= form_tag '/create_tweet_remote', id: "create_tweet", remote: true do %>
		    <%= text_area_tag :content,nil, class: "rounded" %>
		    <%= submit_tag "Create Tweet" %>
		<% end %>

		</br>
		<%= form_tag '/search', method: :get do %>
		    <%=   autocomplete_field_tag 'email', '', autocomplete_user_email_path, :size => 20, :update_elements => {}%>
		    <%= submit_tag 'search user' %>
		<% end %>
		</br>	
		<div class="tweets" id="tweets">
		  <% @tweets.each do |tweet| %>

		<%= render 'tweet' , :tweet => tweet %>

		  <% end %>
		</div>
	</main>
</section>

app/views/home/index_tweets.js.erb
<% @tweets.each do |tweet| %>
$("#tweets").append("<%= escape_javascript(render 'tweet', :tweet => tweet) %>");
<% end %>

app/views/home/profile.html.erb
<section id="mainSection" id="top">
  <aside id="mainAside" class="userInfo">
      <div class="card">
		    <div class="card-content" style="padding: 0px;">
		      <%= image_tag @user.profile_picture_url, class: "profile_picture" %>
		    </div>
		    <div class="card-tabs">
		      <ul class="tabs">
		        <li class="tab"><a class="active" href="#username">Name</a></li>
		        <li class="tab"><a href="#followers">Followers</a></li>
		        <li class="tab"><a href="#following">Following</a></li>
		      </ul>
		    </div>
		    <div class="card-content grey lighten-4">
		      <div id="username"><%=@user.name%></div>
		      <div id="followers"><%=@user.followers.count%></div>
		      <div id="following"><%=@user.followees.count%></div>
		    </div>
		    <% if  current_user != @user %>
			    <% if current_user.is_following?(@user.id)%>
			    <div class="card-action"><%= link_to "UnFollow", url_for(controller: :home, action: :follow, followee_id: @user.id), method: :post %></div>
			    <% else %>
			    <div class="card-action"><%= link_to "Follow", url_for(controller: :home, action: :follow, followee_id: @user.id), method: :post %></div>
			    <% end %>
			   <% end %>
		  </div>
  </aside>
  <main id="mainMain">
		<%= form_tag '/create_tweet_remote', id: "create_tweet", remote: true do %>
		    <%= text_area_tag :content,nil, class: "rounded" %>
		    <%= submit_tag "Create Tweet" %>
		<% end %>

		</br>
		<%= form_tag '/search', method: :get do %>
		    <%=   autocomplete_field_tag 'email', '', autocomplete_user_email_path, :size => 20, :update_elements => {}%>
		    <%= submit_tag 'search user' %>
		<% end %>
		</br>	
		<div class="tweets" id="tweets">
		  <% @tweets.each do |tweet| %>

		<%= render 'tweet' , :tweet => tweet %>

		  <% end %>
		</div>
	</main>
</section>

app/views/home/update_picture.html.erb
<section id="mainSection" id="top">
  <aside id="mainAside" class="userInfo">
    
      <div class="card">
        <div class="card-content" style="padding: 0px;">
          <%= image_tag current_user.profile_picture_url, class: "profile_picture" %>
        </div>
        <div class="card-tabs">
          <ul class="tabs">
            <li class="tab"><a class="active" href="#username">Name</a></li>
            <li class="tab"><a href="#followers">Followers</a></li>
            <li class="tab"><a href="#following">Following</a></li>
          </ul>
        </div>
        <div class="card-content grey lighten-4">
          <div id="username"><%=current_user.name%></div>
          <div id="followers"><%=current_user.followers.count%></div>
          <div id="following"><%=current_user.followees.count%></div>
        </div>
      </div>
  </aside>
  <main id="mainMain">
		<div class="form white hoverable z-depth-2">
			<p class="form-heading">Update Profile Picture</p>
			</br>
			<%= form_tag url_for(controller: 'home', action: 'save_picture'), :multipart => true do %>
					<div class="file-field input-field col s12 m6 l6">
		        <div class="btn">
		          <span>Profile Picture</span>
		          <%= file_field_tag :profile_picture, {class: 'file_select', onchange: "validateImageFiles(this);", data: { max_file_size: 2.megabytes} }%>
		        </div>
		        <div class="file-path-wrapper">
		          <input class="file-path validate" type="text">
		        </div>
		      </div>

			    <%#= file_field_tag :profile_picture, required: true %>
			    <%= submit_tag "Update" %>
			<% end %>
		</div>
	</main>
</section>

app/views/home/users.html.erb
<%= render 'users', :users => @users %>